allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build/${rootProject.name}"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app") // 필요시만 사용
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

tasks.register("cleanAll", Delete) {
    delete subprojects*.buildDir
}