// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMHNq11KA3BvT1axdMMljvwcrG-fFVM1s',
    appId: '1:842590652193:web:7690ae1211b717c5b1a060',
    messagingSenderId: '842590652193',
    projectId: 'nesysworks',
    authDomain: 'nesysworks.firebaseapp.com',
    databaseURL: 'https://nesysworks-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nesysworks.firebasestorage.app',
    measurementId: 'G-HLDZB9NQ24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjDkZ-d8Ko0elnP5WRBsOiWBowkkYCmb4',
    appId: '1:842590652193:android:63c9209589f82a59b1a060',
    messagingSenderId: '842590652193',
    projectId: 'nesysworks',
    databaseURL: 'https://nesysworks-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nesysworks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPgstX3CJVh68lvZu0oIdGNRDmunppoHo',
    appId: '1:842590652193:ios:50b10a7cc409ba96b1a060',
    messagingSenderId: '842590652193',
    projectId: 'nesysworks',
    databaseURL: 'https://nesysworks-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nesysworks.firebasestorage.app',
    iosBundleId: 'kr.plinemotors.nesysworks.nesysworks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPgstX3CJVh68lvZu0oIdGNRDmunppoHo',
    appId: '1:842590652193:ios:50b10a7cc409ba96b1a060',
    messagingSenderId: '842590652193',
    projectId: 'nesysworks',
    databaseURL: 'https://nesysworks-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nesysworks.firebasestorage.app',
    iosBundleId: 'kr.plinemotors.nesysworks.nesysworks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMHNq11KA3BvT1axdMMljvwcrG-fFVM1s',
    appId: '1:842590652193:web:422a19cc1d2892c0b1a060',
    messagingSenderId: '842590652193',
    projectId: 'nesysworks',
    authDomain: 'nesysworks.firebaseapp.com',
    databaseURL: 'https://nesysworks-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nesysworks.firebasestorage.app',
    measurementId: 'G-FHF7P0WMMK',
  );

}